const api="/api",money=v=>Number(v).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
let products=[],categories=[],cart=JSON.parse(localStorage.getItem("valaris-cart")||"[]"),adminKey=sessionStorage.getItem("adminKey")||"",pendingCustomer=null;
const $=s=>document.querySelector(s),toast=m=>{$("#toast").textContent=m;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),2600)};
async function request(url,options={}){const r=await fetch(api+url,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}}),d=r.status===204?null:await r.json();if(!r.ok)throw Error(d?.error||"Não foi possível realizar a operação.");return d}
function go(page){document.querySelectorAll(".page").forEach(e=>e.classList.toggle("active",e.id===page));if(page==="cart")renderCart();if(page==="admin"&&adminKey)loadAdmin();scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll("[data-page]").forEach(e=>e.onclick=x=>{x.preventDefault();go(e.dataset.page)});
async function loadStore(){[products,categories]=await Promise.all([request("/products"),request("/categories")]);const o=categories.map(c=>`<option value="${c.id}">${c.name}</option>`).join("");$("#category-filter").innerHTML='<option value="">Todos os gêneros</option>'+o;$("#product-category").innerHTML='<option value="">Sem gênero</option>'+o;renderProducts()}
function renderProducts(){const t=$("#search").value.toLowerCase(),c=$("#category-filter").value,f=products.filter(p=>(p.name+" "+p.description).toLowerCase().includes(t)&&(!c||String(p.category_id)===c));$("#products").innerHTML=f.length?f.map(p=>`<article class="product" onclick="openProduct(${p.id})"><div class="cover-wrap"><img src="${p.image_url||"https://placehold.co/400x600?text=Livro"}" alt="Capa de ${p.name}"></div><div class="product-body"><span class="muted">${p.category_name||"Literatura"}</span><h3>${p.name}</h3><p>${p.description}</p><div class="product-footer"><div><div class="price">${money(p.price)}</div><small>${p.stock} em estoque</small></div><button onclick="event.stopPropagation();addCart(${p.id})" ${p.stock?"":"disabled"}>Adicionar</button></div></div></article>`).join(""):"<p>Nenhum livro encontrado.</p>"}
$("#search").oninput=renderProducts;$("#category-filter").onchange=renderProducts;
window.openProduct=id=>{const p=products.find(x=>x.id===id);$("#product-view").innerHTML=`<div class="detail-cover"><img src="${p.image_url}" alt="${p.name}"></div><div class="detail-info"><span class="eyebrow">${p.category_name||"Literatura"}</span><h2>${p.name}</h2><div>★★★★★</div><div class="detail-price">${money(p.price)}</div><p>${p.description}</p><small>${p.stock} unidades disponíveis</small><div class="detail-actions"><button class="primary" onclick="addCart(${p.id});go('cart')">Comprar</button><button class="outline" onclick="addCart(${p.id})">Adicionar à sacola</button></div></div>`;go("product-detail")};
window.addCart=id=>{const p=products.find(x=>x.id===id),i=cart.find(x=>x.product_id===id);if(i){if(i.quantity>=p.stock)return toast("Limite do estoque atingido.");i.quantity++}else cart.push({product_id:id,quantity:1,name:p.name,price:p.price,stock:p.stock,image_url:p.image_url});saveCart();toast("Livro adicionado à sacola.")};
function saveCart(){localStorage.setItem("valaris-cart",JSON.stringify(cart));$("#cart-count").textContent=cart.reduce((s,i)=>s+i.quantity,0)}
window.changeQuantity=(id,v)=>{const i=cart.find(x=>x.product_id===id);i.quantity=Math.max(1,Math.min(Number(v),i.stock));saveCart();renderCart()};
window.removeCart=id=>{cart=cart.filter(x=>x.product_id!==id);saveCart();renderCart()};
function shipping(){return Number(document.querySelector('input[name="shipping"]:checked')?.value||0)}
function renderCart(){const subtotal=cart.reduce((s,i)=>s+i.price*i.quantity,0),freight=cart.length?shipping():0;$("#cart-items").innerHTML=cart.length?cart.map(i=>`<div class="cart-row"><img src="${i.image_url}" alt="" style="width:55px;height:78px;object-fit:contain"><div><b>${i.name}</b><div class="muted">${money(i.price)}</div></div><input type="number" min="1" max="${i.stock}" value="${i.quantity}" onchange="changeQuantity(${i.product_id},this.value)"><button class="danger" onclick="removeCart(${i.product_id})">×</button></div>`).join(""):"<p>Sua sacola está vazia.</p>";$("#products-total").textContent=money(subtotal);$("#shipping-total").textContent=money(freight);$("#cart-total").textContent=money(subtotal+freight)}
document.querySelectorAll('input[name="shipping"]').forEach(e=>e.onchange=renderCart);$("#calculate-shipping").onclick=()=>toast($("#zip-code").value.length>=8?"Frete calculado para o CEP informado.":"Digite um CEP válido.");
$("#checkout-form").onsubmit=e=>{e.preventDefault();if(!cart.length)return toast("Adicione livros à sacola.");pendingCustomer=Object.fromEntries(new FormData(e.target));go("payment")};
document.querySelectorAll("[data-payment]").forEach(b=>b.onclick=()=>finishSale(b.dataset.payment));
async function finishSale(method){if(!pendingCustomer)return go("cart");try{const s=await request("/sales",{method:"POST",body:JSON.stringify({customer:pendingCustomer,items:cart.map(({product_id,quantity})=>({product_id,quantity}))})});localStorage.setItem("valaris-last-order",JSON.stringify({id:s.id,email:pendingCustomer.email,method}));cart=[];saveCart();$("#checkout-form").reset();pendingCustomer=null;await loadStore();toast("Pedido confirmado com "+method+"!");go("tracking")}catch(e){toast(e.message)}}
$("#copy-tracking").onclick=async()=>{const o=JSON.parse(localStorage.getItem("valaris-last-order")||"{}"),code="VAL"+String(o.id||1).padStart(6,"0")+"BR";try{await navigator.clipboard.writeText(code);toast("Código "+code+" copiado.")}catch{toast("Código de rastreio: "+code)}};
$("#login-form").onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));localStorage.setItem("valaris-user",d.email);toast("Login realizado com sucesso.");go("store")};$("#create-account").onclick=e=>{e.preventDefault();toast("Cadastro demonstrativo: use qualquer e-mail e senha.")};
$("#orders-form").onsubmit=e=>{e.preventDefault();loadOrders($("#orders-email").value)};
async function loadOrders(email){try{const sales=await request("/sales?email="+encodeURIComponent(email));$("#orders-list").innerHTML=sales.length?sales.map(orderCard).join(""):"<div class='panel'>Nenhum pedido encontrado.</div>"}catch(e){toast(e.message)}}
function orderCard(s){return `<article class="order"><div class="order-head"><div><b>Pedido #${s.id}</b><div class="muted">${new Date(s.created_at+"Z").toLocaleString("pt-BR")}</div></div><span class="badge">${s.status}</span></div>${s.items.map(i=>`<p>${i.quantity}x ${i.name} — ${money(i.quantity*i.unit_price)}</p>`).join("")}<strong>Total: ${money(s.total)}</strong></article>`}
$("#admin-enter").onclick=async()=>{adminKey=$("#admin-key").value;try{await request("/products?all=1",{headers:{"x-admin-key":adminKey}});sessionStorage.setItem("adminKey",adminKey);loadAdmin()}catch(e){adminKey="";toast(e.message)}};
$("#admin-exit").onclick=()=>{adminKey="";sessionStorage.removeItem("adminKey");$("#admin-area").hidden=true;$("#admin-login").hidden=false};
async function loadAdmin(){try{const [all,sales]=await Promise.all([request("/products?all=1",{headers:{"x-admin-key":adminKey}}),request("/sales",{headers:{"x-admin-key":adminKey}})]);$("#admin-login").hidden=true;$("#admin-area").hidden=false;$("#stat-products").textContent=all.filter(p=>p.active).length;$("#stat-sales").textContent=sales.length;$("#stat-revenue").textContent=money(sales.reduce((s,v)=>s+v.total,0));$("#admin-products").innerHTML=all.map(p=>`<div class="admin-row"><div><b>${p.name}</b><div class="muted">${money(p.price)} · estoque ${p.stock} · ${p.active?"ativo":"inativo"}</div></div><div><button onclick='editProduct(${JSON.stringify(p)})'>Editar</button> ${p.active?`<button class="danger" onclick="disableProduct(${p.id})">Desativar</button>`:""}</div></div>`).join("");$("#admin-sales").innerHTML=sales.length?sales.map(s=>`<div class="admin-row"><div><b>#${s.id} · ${s.customer_name}</b><div class="muted">${s.email} · ${money(s.total)}</div></div><select onchange="changeStatus(${s.id},this.value)">${["Confirmada","Em preparação","Enviada","Concluída","Cancelada"].map(v=>`<option ${v===s.status?"selected":""}>${v}</option>`).join("")}</select></div>`).join(""):"Nenhum pedido."}catch(e){$("#admin-exit").click();toast(e.message)}}
window.editProduct=p=>{const f=$("#product-form");Object.keys(p).forEach(k=>{if(f.elements[k])f.elements[k].value=p[k]??""});$("#product-title").textContent="Editar livro";f.scrollIntoView({behavior:"smooth"})};
$("#cancel-edit").onclick=()=>{$("#product-form").reset();$("#product-form").elements.id.value="";$("#product-title").textContent="Cadastrar livro"};
$("#product-form").onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target)),id=data.id;delete data.id;data.price=Number(data.price);data.stock=Number(data.stock);data.category_id=data.category_id?Number(data.category_id):null;data.active=1;try{await request(id?"/products/"+id:"/products",{method:id?"PUT":"POST",headers:{"x-admin-key":adminKey},body:JSON.stringify(data)});toast("Livro salvo.");$("#cancel-edit").click();await loadStore();loadAdmin()}catch(x){toast(x.message)}};
window.disableProduct=async id=>{if(!confirm("Deseja desativar este livro?"))return;try{await request("/products/"+id,{method:"DELETE",headers:{"x-admin-key":adminKey}});toast("Livro desativado.");await loadStore();loadAdmin()}catch(e){toast(e.message)}};
window.changeStatus=async(id,status)=>{try{await request("/sales/"+id+"/status",{method:"PATCH",headers:{"x-admin-key":adminKey},body:JSON.stringify({status})});toast("Status atualizado.")}catch(e){toast(e.message)}};
saveCart();loadStore().catch(e=>toast("Não foi possível conectar à API: "+e.message));